version: '3.8'
services:
  api:
    image: chat-image
    build:
      context: .
    container_name: chat-api
    ports:
      - "80:80"
    env_file:
      - ./.env
    environment:
      API_KEY: '${API_KEY}'
      CHAT_GPT_IMAGE_URL: '${CHAT_GPT_IMAGE_URL}'
      CHAT_GPT_MULTICHAT_URL: '${CHAT_GPT_MULTICHAT_URL}'
      CHAT_GPT_URL: '${CHAT_GPT_URL}'
      GPT_PASSWORD: '${GPT_PASSWORD}'
      GPT_USER_NAME: '${GPT_USER_NAME}'
      MAX_TOKENS: '${MAX_TOKENS}'
      MODEL: '${MODEL}'
      MULTICHAT_MODEL: '${MULTICHAT_MODEL}'
      ORIGIN: '${ORIGIN}'
      TEMPERATURE: '${TEMPERATURE}'
      TOP_P: '${TOP_P}'