server:
  port: 8080
chatgpt:
  api-key: ${API_KEY}
  url: ${CHAT_GPT_URL}
  model: ${MODEL}
  max-tokens: ${MAX_TOKENS}
  temperature: ${TEMPERATURE}
  top-p: ${TOP_P}
  security:
    user-name: ${GPT_USER_NAME}
    password: ${GPT_PASSWORD}
    origin: ${ORIGIN}